version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
    ports:
      - $DB_HOST:$DB_PORT:5432
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
